name: midterm_gallery
description: "A smart gallery app for Android and Windows"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  path: ^1.9.0
  image: ^4.2.0
  path_provider: ^2.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  permission_handler: ^11.3.1
  hive_generator: ^2.0.1
  crypto: ^3.0.5
  google_mlkit_image_labeling: ^0.12.1
  tflite_flutter: ^0.11.0
  device_info_plus: ^10.1.2
  onnxruntime: # https://stackoverflow.com/a/54023220
    git:
      url: https://github.com/cowboyeric/onnxruntime_flutter.git
      ref: main 
  collection: ^1.18.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/models/mobileclip_b/